# Generated by Django 2.2.3 on 2020-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='class_ch',
            field=models.IntegerField(choices=[(11, '全栈一期'), (22, '全栈二期')], default=11, verbose_name='性别'),
        ),
    ]
